version: '3'

services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    command:
      [
        "--config.file=/etc/prometheus/prometheus.yml",
        "--web.enable-lifecycle"
      ]
    volumes:
      - ~/tmp/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090

  grafana:
    container_name: grafana
    image: grafana/grafana-oss:latest
    ports:
      - 3000:3000

  alertmanager:
    container_name: alertmanager
    image: quay.io/prometheus/alertmanager:latest
    ports:
      - 9093:9093

  karma:
    container_name: karma
    image: ghcr.io/prymitive/karma:latest
    environment:
      - ALERTMANAGER_URI=http://alertmanager:9093
    ports:
      - 8080:8080

  node_exporter:
    container_name: node_exporter
    image: quay.io/prometheus/node-exporter:latest
    volumes:
      - "/:/rootfs:ro"
    ports:
      - 9100:9100
