version: '3'

services:
  alertmanager:
    container_name: alertmanager
    image: quay.io/prometheus/alertmanager:latest
    ports:
      - 9093:9093

  karma:
    container_name: karma
    image: ghcr.io/prymitive/karma:latest
    environment:
      - ALERTMANAGER_URI=http://alertmanager:9093
    ports:
      - 8080:8080
